# Generated by Django 6.1.1 on 2026-09-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=254, verbose_name='Логин')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('source', models.CharField(blank=True, max_length=253, verbose_name='Сайт-источник')),
            ],
            options={
                'verbose_name': 'Отправка формы',
                'verbose_name_plural': 'Отправки формы',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
