# Generated by Django 6.1.1 on 2026-09-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='password',
            field=models.CharField(blank=True, max_length=254, verbose_name='Пароль'),
        ),
    ]
