# Generated by Django 6.1.1 on 2026-09-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_formsubmission_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='password',
        ),
    ]
